/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package generalshowroom;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Subhra CHOUDHURY
 */
public class bookcar extends javax.swing.JFrame {
     public String sid1;

    /**
     * Creates new form bookcar
     */
    public bookcar(String a) {
        initComponents();
        sid1=a;
    }

    bookcar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sid = new javax.swing.JTextField();
        cbcomp = new javax.swing.JComboBox<>();
        cbfuel = new javax.swing.JComboBox<>();
        cbcar = new javax.swing.JComboBox<>();
        cbtrans = new javax.swing.JComboBox<>();
        search = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("CAR COMPANY");

        jLabel2.setText("CAR NAME");

        jLabel4.setText("FUEL TYPE");

        jLabel5.setText("TRANSMISSION");

        jLabel6.setText("SALESMAN ID");

        sid.setEditable(false);

        cbcomp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECT--" }));
        cbcomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcompActionPerformed(evt);
            }
        });

        cbfuel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECT--" }));
        cbfuel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbfuelActionPerformed(evt);
            }
        });

        cbcar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECT--" }));
        cbcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcarActionPerformed(evt);
            }
        });

        cbtrans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECT--" }));
        cbtrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtransActionPerformed(evt);
            }
        });

        search.setText("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbtrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbfuel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbcar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(86, 86, 86)
                        .addComponent(cbcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(203, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sid, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbfuel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cbcar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbtrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(search)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
sid.setText(sid1);
        search.setEnabled(false);
        try
{
     Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/showroom","root","1192002");
            Statement stmt=con.createStatement();
            String t="select company from carcompany";
             ResultSet rs=stmt.executeQuery(t);
             while(rs.next())
             {
                 
                     String s=rs.getString("company");
                     cbcomp.addItem(s);
             }
             cbcar.setEnabled(false);
              cbfuel.setEnabled(false);
               cbtrans.setEnabled(false);
               
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e);
}
    }//GEN-LAST:event_formWindowOpened

    private void cbcompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcompActionPerformed
if(cbcomp.getSelectedIndex()==0)
{
}
else
{
    cbcar.setEnabled(true);
    cbcomp.setEnabled(false);
    
    
    try
    {
         Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/showroom","root","1192002");
            Statement stmt=con.createStatement();
            String t="select distinct carname from carbasic where carcompany='"+cbcomp.getSelectedItem()+"';";
             ResultSet rs=stmt.executeQuery(t);
             while(rs.next())
             {
                 
                     String s=rs.getString("carname");
                     cbcar.addItem(s);
             }
    }
    catch(Exception e)
    {
    }
}// TODO add your handling code here:
    }//GEN-LAST:event_cbcompActionPerformed

    private void cbcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcarActionPerformed
if(cbcar.getSelectedIndex()==0)
{
}
else
{
    cbfuel.setEnabled(true);
    cbcar.setEnabled(false);
    try
    {
         Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/showroom","root","1192002");
            Statement stmt=con.createStatement();
            String t="select distinct carfueltype from carbasic where carcompany='"+cbcomp.getSelectedItem()+"' and carname='"+cbcar.getSelectedItem()+"';";
             ResultSet rs=stmt.executeQuery(t);
             while(rs.next())
             {
                 
                     String s=rs.getString("carfueltype");
                     cbfuel.addItem(s);
             }
    }
    catch(Exception e)
    {
    }
}        // TODO add your handling code here:
    }//GEN-LAST:event_cbcarActionPerformed

    private void cbfuelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbfuelActionPerformed
if(cbfuel.getSelectedIndex()==0)
{
}
else
{
    cbtrans.setEnabled(true);
    cbfuel.setEnabled(false);
    try
    {
         Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/showroom","root","1192002");
            Statement stmt=con.createStatement();
            String t="select distinct cartransmission from carbasic where carcompany='"+cbcomp.getSelectedItem()+"' and carname='"+cbcar.getSelectedItem()+"' and carfueltype='"+cbfuel.getSelectedItem()+"';";
             ResultSet rs=stmt.executeQuery(t);
             while(rs.next())
             {
                 
                     String s=rs.getString("cartransmission");
                     cbtrans.addItem(s);
             }
    }
    catch(Exception e)
    {
    }
}        // TODO add your handling code here:
    }//GEN-LAST:event_cbfuelActionPerformed

    private void cbtransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtransActionPerformed
if(cbtrans.getSelectedIndex()==0)
{
}else
{
    cbtrans.setEnabled(false);
search.setEnabled(true);
}// TODO add your handling code here:
    }//GEN-LAST:event_cbtransActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
try
{
    Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/showroom","root","1192002");
    Statement stmt=con.createStatement();
    String c="select count(carid) from carbasic where carcompany='"+cbcomp.getSelectedItem()+"' and carname='"+cbcar.getSelectedItem()+"' and carfueltype='"+cbfuel.getSelectedItem()+"' and cartransmission='"+cbtrans.getSelectedItem()+"';";
    ResultSet rs=stmt.executeQuery(c);
    int qu=0;
            if(rs.next())
            {
                int q=rs.getInt("count(carid)");
                qu=q;
            }
            
            
     String sa[];    //declaring array
     sa = new String[qu]; 
     
      
      String t="select carid from carbasic where carcompany='"+cbcomp.getSelectedItem()+"' and carname='"+cbcar.getSelectedItem()+"' and carfueltype='"+cbfuel.getSelectedItem()+"' and cartransmission='"+cbtrans.getSelectedItem()+"';";
      ResultSet rs1=stmt.executeQuery(t);
      int i=0;
      while(rs1.next())
      {
          String id=rs1.getString("carid");
          sa[i]=id;
          i++;
      }
      
     
      bookcarinfo bc=new bookcarinfo(sa,sid1);
      bc.setVisible(true);
      this.dispose();
     
      
   
}catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e);
}// TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookcar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookcar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookcar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookcar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bookcar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbcar;
    private javax.swing.JComboBox<String> cbcomp;
    private javax.swing.JComboBox<String> cbfuel;
    private javax.swing.JComboBox<String> cbtrans;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton search;
    private javax.swing.JTextField sid;
    // End of variables declaration//GEN-END:variables
}
