/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package generalshowroom;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Subhra CHOUDHURY
 */
public class newcarmain extends javax.swing.JFrame {
    public String cid;

    /**
     * Creates new form newcarmain
     */
    public newcarmain(String idd) {
        initComponents();
        cid=idd;
    }

    newcarmain() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        buttonGroup13 = new javax.swing.ButtonGroup();
        buttonGroup14 = new javax.swing.ButtonGroup();
        buttonGroup15 = new javax.swing.ButtonGroup();
        buttonGroup16 = new javax.swing.ButtonGroup();
        buttonGroup17 = new javax.swing.ButtonGroup();
        buttonGroup18 = new javax.swing.ButtonGroup();
        buttonGroup19 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        carid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        a0 = new javax.swing.JRadioButton();
        a2 = new javax.swing.JRadioButton();
        a4 = new javax.swing.JRadioButton();
        a6 = new javax.swing.JRadioButton();
        a8 = new javax.swing.JRadioButton();
        a10 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        y1 = new javax.swing.JCheckBox();
        y2 = new javax.swing.JCheckBox();
        y3 = new javax.swing.JCheckBox();
        y4 = new javax.swing.JCheckBox();
        y5 = new javax.swing.JCheckBox();
        y6 = new javax.swing.JCheckBox();
        y7 = new javax.swing.JCheckBox();
        y8 = new javax.swing.JCheckBox();
        y9 = new javax.swing.JCheckBox();
        y10 = new javax.swing.JCheckBox();
        y11 = new javax.swing.JCheckBox();
        y12 = new javax.swing.JCheckBox();
        y13 = new javax.swing.JCheckBox();
        y14 = new javax.swing.JCheckBox();
        y15 = new javax.swing.JCheckBox();
        y16 = new javax.swing.JCheckBox();
        y17 = new javax.swing.JCheckBox();
        y18 = new javax.swing.JCheckBox();

        jRadioButton7.setText("YES");

        jRadioButton8.setText("NO");

        jRadioButton11.setText("YES");

        jRadioButton12.setText("NO");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("CAR ID");

        carid.setEditable(false);
        carid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caridActionPerformed(evt);
            }
        });

        jLabel2.setText("MAIN  FEATURES");

        jLabel4.setText("SUNROOF");

        jLabel5.setText("PUSH BUTTON START/STOP");

        jLabel6.setText("NAVIGATION SYSTEM");

        jLabel7.setText("AIRBAGS");

        jLabel8.setText("POWER STEERINGS");

        jLabel9.setText("ABS");

        jLabel10.setText("AC");

        jLabel11.setText("FOG LAMP");

        jLabel3.setText("REVERSE VIEW CAMERA");

        jLabel12.setText("360° CAMERA");

        jLabel13.setText("SPEED-SENSITIVE AUTO DOOR LOCK");

        jLabel14.setText("ANTI-THEFT ALARM");

        jLabel15.setText("CHILD LOCK");

        jLabel16.setText("ADJUSTABLE SEAT");

        jLabel17.setText("HILL CONTROL");

        jLabel18.setText("REAR WIPER AND WASHER");

        jLabel19.setText("SPEAKERS");

        jLabel20.setText("TWEETERS");

        jLabel21.setText("STEERING MOUNTED CONTROLS");

        buttonGroup18.add(a0);
        a0.setText("0");
        a0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a0ActionPerformed(evt);
            }
        });

        buttonGroup18.add(a2);
        a2.setText("2");
        a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a2ActionPerformed(evt);
            }
        });

        buttonGroup18.add(a4);
        a4.setText("4");
        a4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a4ActionPerformed(evt);
            }
        });

        buttonGroup18.add(a6);
        a6.setText("6");
        a6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a6ActionPerformed(evt);
            }
        });

        buttonGroup18.add(a8);
        a8.setText("8");
        a8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a8ActionPerformed(evt);
            }
        });

        buttonGroup18.add(a10);
        a10.setText("10 OR MORE");
        a10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a10ActionPerformed(evt);
            }
        });

        jButton1.setText("NEXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel3)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19)
                            .addComponent(jLabel21))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(y9)
                            .addComponent(y10)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(y8)
                                    .addComponent(y7)
                                    .addComponent(y6)
                                    .addComponent(y5)
                                    .addComponent(y4)
                                    .addComponent(y3)
                                    .addComponent(y2)
                                    .addComponent(y1))
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addGap(123, 123, 123)
                                        .addComponent(y18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(43, 43, 43)
                                        .addComponent(y17))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(86, 86, 86)
                                        .addComponent(y16))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(80, 80, 80)
                                        .addComponent(y15))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(108, 108, 108)
                                        .addComponent(y14))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(126, 126, 126)
                                        .addComponent(y13))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(157, 157, 157)
                                        .addComponent(y12))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(42, 42, 42)
                                        .addComponent(y11)))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(37, 37, 37)
                                .addComponent(carid, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(a0)
                            .addComponent(a2)
                            .addComponent(a4)
                            .addComponent(a6)
                            .addComponent(a8)
                            .addComponent(a10))
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(133, 133, 133))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(carid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(y6)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(y1))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(y2))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(y3)
                                    .addComponent(jLabel8))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(y5)))
                                    .addComponent(y4))
                                .addGap(35, 35, 35)
                                .addComponent(jLabel13))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(a2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(a4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(a6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(120, 120, 120)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(y7))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(y8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addComponent(a0, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(y12))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(y13))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel12))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(y14)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(jLabel16))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(y16)))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(y17))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(y18)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(a8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(y15))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(a10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(y11))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(y9))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21)
                            .addComponent(y10))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(52, 52, 52))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void a0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a0ActionPerformed

    private void a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a2ActionPerformed

    private void a4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a4ActionPerformed

    private void a6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a6ActionPerformed

    private void a8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a8ActionPerformed

    private void a10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a10ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
carid.setText(""+cid);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void caridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caridActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int resp=JOptionPane.showConfirmDialog(this, "DO YOU WANT TO SAVE THE FEATURES? ");

        if(resp==JOptionPane.YES_OPTION)  
        {
            if(a0.isSelected()==false && a2.isSelected()==false && a4.isSelected()==false && a6.isSelected()==false && a8.isSelected()==false && a10.isSelected()==false )
            {
                JOptionPane.showMessageDialog(null,"PLEASE SELECT NO. OF AIRBAGS");
            }else
            {
        try{
    Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/showroom","root","1192002");
            Statement stmt=con.createStatement();
    if(y1.isSelected()==true)
    {
          
            String s1="Insert into carmainyes values('"+cid+"','"+"sunroof"+"'); ";
            stmt.executeUpdate(s1);
    }else
    {
        String s2="Insert into carmainno values('"+cid+"','"+"sunroof"+"'); ";
        stmt.executeUpdate(s2);
    }
     if(y2.isSelected()==true)
    {
          
            String s3="Insert into carmainyes values('"+cid+"','"+"NAVIGATION SYSTEM"+"'); ";
            stmt.executeUpdate(s3);
    }else
    {
        String s4="Insert into carmainno values('"+cid+"','"+"NAVIGATION SYSTEM"+"'); ";
        stmt.executeUpdate(s4);
    }
      if(y3.isSelected()==true)
    {
          
            String s5="Insert into carmainyes values('"+cid+"','"+"POWER STEERINGS"+"'); ";
            stmt.executeUpdate(s5);
    }else 
    {
        String s6="Insert into carmainno values('"+cid+"','"+"POWER STEERINGS"+"'); ";
        stmt.executeUpdate(s6);
    }
       if(y4.isSelected()==true)
    {
          
            String s7="Insert into carmainyes values('"+cid+"','"+"AC"+"'); ";
            stmt.executeUpdate(s7);
    }else 
    {
        String s8="Insert into carmainno values('"+cid+"','"+"AC"+"'); ";
        stmt.executeUpdate(s8);
    }
        if(y5.isSelected()==true)
    {
          
            String s9="Insert into carmainyes values('"+cid+"','"+"REVERSE VIEW CAMERA"+"'); ";
            stmt.executeUpdate(s9);
    }else 
    {
        String s10="Insert into carmainno values('"+cid+"','"+"REVERSE VIEW CAMERA"+"'); ";
        stmt.executeUpdate(s10);
    }
        if(y6.isSelected()==true)
    {
          
            String s11="Insert into carmainyes values('"+cid+"','"+"SPEED-SENSITIVE AUTO DOOR LOCK"+"'); ";
            stmt.executeUpdate(s11);
    }else  
    {
        String s12="Insert into carmainno values('"+cid+"','"+"SPEED-SENSITIVE AUTO DOOR LOCK"+"'); ";
        stmt.executeUpdate(s12);
    }
         if(y7.isSelected()==true)
    {
          
            String s13="Insert into carmainyes values('"+cid+"','"+"CHILD LOCK"+"'); ";
            stmt.executeUpdate(s13);
    }else  
    {
        String s14="Insert into carmainno values('"+cid+"','"+"CHILD LOCK"+"'); ";
        stmt.executeUpdate(s14);
    }
         if(y8.isSelected()==true)
    {
          
            String s15="Insert into carmainyes values('"+cid+"','"+"HILL CONTROL"+"'); ";
            stmt.executeUpdate(s15);
    }else 
    {
        String s16="Insert into carmainno values('"+cid+"','"+"HILL CONTROL"+"'); ";
        stmt.executeUpdate(s16);
    }
         if(y9.isSelected()==true)
    {
          
            String s17="Insert into carmainyes values('"+cid+"','"+"SPEAKERS"+"'); ";
            stmt.executeUpdate(s17);
    }else
    {
        String s18="Insert into carmainno values('"+cid+"','"+"SPEAKERS"+"'); ";
        stmt.executeUpdate(s18);
    }
         if(y10.isSelected()==true)
    {
          
            String s19="Insert into carmainyes values('"+cid+"','"+"STEERING MOUNTED CONTROLS"+"'); ";
            stmt.executeUpdate(s19);
    }else 
    {
        String s20="Insert into carmainno values('"+cid+"','"+"STEERING MOUNTED CONTROLS"+"'); ";
        stmt.executeUpdate(s20);
    }
         if(y11.isSelected()==true)
    {
          
            String s21="Insert into carmainyes values('"+cid+"','"+"PUSH BUTTON START/STOP"+"'); ";
            stmt.executeUpdate(s21);
    }else 
    {
        String s22="Insert into carmainno values('"+cid+"','"+"PUSH BUTTON START/STOP"+"'); ";
        stmt.executeUpdate(s22);
    }
          if(y12.isSelected()==true)
    {
          
            String s23="Insert into carmainyes values('"+cid+"','"+"ABS"+"'); ";
            stmt.executeUpdate(s23);
    }else 
    {
        String s24="Insert into carmainno values('"+cid+"','"+"ABS"+"'); ";
        stmt.executeUpdate(s24);
    }
           if(y13.isSelected()==true)
    {
          
            String s25="Insert into carmainyes values('"+cid+"','"+"FOG LAMP"+"'); ";
            stmt.executeUpdate(s25);
    }else 
    {
        String s26="Insert into carmainno values('"+cid+"','"+"FOG LAMP"+"'); ";
        stmt.executeUpdate(s26);
    }
           if(y14.isSelected()==true)
    {
          
            String s27="Insert into carmainyes values('"+cid+"','"+"360° CAMERA"+"'); ";
            stmt.executeUpdate(s27);
    }else 
    {
        String s28="Insert into carmainno values('"+cid+"','"+"360° CAMERA"+"'); ";
        stmt.executeUpdate(s28);
    }
           if(y15.isSelected()==true)
    {
          
            String s29="Insert into carmainyes values('"+cid+"','"+"ANTI-THEFT ALARM"+"'); ";
            stmt.executeUpdate(s29);
    }else 
    {
        String s30="Insert into carmainno values('"+cid+"','"+"ANTI-THEFT ALARM"+"'); ";
        stmt.executeUpdate(s30);
    }
            if(y16.isSelected()==true)
    {
          
            String s31="Insert into carmainyes values('"+cid+"','"+"ADJUSTABLE SEAT"+"'); ";
            stmt.executeUpdate(s31);
    }else 
    {
        String s32="Insert into carmainno values('"+cid+"','"+"ADJUSTABLE SEAT"+"'); ";
        stmt.executeUpdate(s32);
    }    
            if(y17.isSelected()==true)
    {
          
            String s33="Insert into carmainyes values('"+cid+"','"+"REAR WIPER AND WASHER"+"'); ";
            stmt.executeUpdate(s33);
    }else 
    {
        String s34="Insert into carmainno values('"+cid+"','"+"REAR WIPER AND WASHER"+"'); ";
        stmt.executeUpdate(s34);
    }
            if(y18.isSelected()==true)
    {
          
            String s35="Insert into carmainyes values('"+cid+"','"+"TWEETERS"+"'); ";
            stmt.executeUpdate(s35);
    }else 
    {
        String s36="Insert into carmainno values('"+cid+"','"+"TWEETERS"+"'); ";
        stmt.executeUpdate(s36);
    }
            if(a0.isSelected()==true)
            {
                String ab1="Insert into carmainairbags values('"+cid+"','"+"0"+"')";
                stmt.executeUpdate(ab1);
            }else if(a2.isSelected()==true)
            {
                String ab2="Insert into carmainairbags values('"+cid+"','"+"2"+"')";
                 stmt.executeUpdate(ab2);
            }else if(a4.isSelected()==true)
            {
                String ab3="Insert into carmainairbags values('"+cid+"','"+"4"+"')";
                 stmt.executeUpdate(ab3);
            }else if(a6.isSelected()==true)
                {
                String ab4="Insert into carmainairbags values('"+cid+"','"+"6"+"')";
                 stmt.executeUpdate(ab4);
            }else if(a8.isSelected()==true)
                {
                String ab5="Insert into carmainairbags values('"+cid+"','"+"8"+"')";
                 stmt.executeUpdate(ab5);
            }else if(a10.isSelected()==true)
                {
                String ab6="Insert into carmainairbags values('"+cid+"','"+"10"+"')";
                 stmt.executeUpdate(ab6);
            }
                JOptionPane.showMessageDialog(null,"FEATURES ADDED");
                newcaradditional nc=new newcaradditional(cid);
                nc.setVisible(true);
                this.dispose();
         
    
}catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e);
}
            }      }// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newcarmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newcarmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newcarmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newcarmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newcarmain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton a0;
    private javax.swing.JRadioButton a10;
    private javax.swing.JRadioButton a2;
    private javax.swing.JRadioButton a4;
    private javax.swing.JRadioButton a6;
    private javax.swing.JRadioButton a8;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup13;
    private javax.swing.ButtonGroup buttonGroup14;
    private javax.swing.ButtonGroup buttonGroup15;
    private javax.swing.ButtonGroup buttonGroup16;
    private javax.swing.ButtonGroup buttonGroup17;
    private javax.swing.ButtonGroup buttonGroup18;
    private javax.swing.ButtonGroup buttonGroup19;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JTextField carid;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JCheckBox y1;
    private javax.swing.JCheckBox y10;
    private javax.swing.JCheckBox y11;
    private javax.swing.JCheckBox y12;
    private javax.swing.JCheckBox y13;
    private javax.swing.JCheckBox y14;
    private javax.swing.JCheckBox y15;
    private javax.swing.JCheckBox y16;
    private javax.swing.JCheckBox y17;
    private javax.swing.JCheckBox y18;
    private javax.swing.JCheckBox y2;
    private javax.swing.JCheckBox y3;
    private javax.swing.JCheckBox y4;
    private javax.swing.JCheckBox y5;
    private javax.swing.JCheckBox y6;
    private javax.swing.JCheckBox y7;
    private javax.swing.JCheckBox y8;
    private javax.swing.JCheckBox y9;
    // End of variables declaration//GEN-END:variables
}
