/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package generalshowroom;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Subhra CHOUDHURY
 */
public class saleshistory extends javax.swing.JFrame {

    /**
     * Creates new form saleshistory
     */
    public saleshistory() {
        initComponents();
         setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cb = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtcomp = new javax.swing.JTextField();
        txtcar = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("CAR ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 71, -1, -1));

        cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECT--" }));
        cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActionPerformed(evt);
            }
        });
        getContentPane().add(cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 68, 102, -1));

        jLabel2.setText("CAR COMPANY");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 109, -1, -1));

        jLabel3.setText("CAR NAME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 146, -1, -1));

        txtcomp.setEditable(false);
        txtcomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcompActionPerformed(evt);
            }
        });
        getContentPane().add(txtcomp, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 106, 180, -1));

        txtcar.setEditable(false);
        getContentPane().add(txtcar, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 143, 180, -1));

        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 670, 73, -1));
        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 181, -1, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SR NO.", "C_NAME", "LICENSE NO.", "PHONE NO.", "ADD_LINE 1", "AREA", "LANDMARK", "CITY", "STATE", "PINCODE", "FLOORMAT", "SEAT COVER", "SW_COVER", "BASIC KIT", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 1301, 441));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
try
{
     Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/showroom","root","1192002");
            Statement stmt=con.createStatement();
            String s="Select * from carbasic;";
            ResultSet rs=stmt.executeQuery(s);
            while(rs.next())
            {
                String i=rs.getString("carid");
                cb.addItem(i);
            }
            
}catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e);
}// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void txtcompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcompActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcompActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
adminmenu m=new adminmenu();
m.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActionPerformed
DefaultTableModel my_model=(DefaultTableModel) table.getModel();
                 my_model.setRowCount(0);
        if(cb.getSelectedIndex()==0)
{
     my_model.setRowCount(0);
     txtcomp.setText("");
                txtcar.setText("");
                
}else
{
    
 try
{
     Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/showroom","root","1192002");
            Statement stmt=con.createStatement();
            String s="Select * from carbasic where carid='"+cb.getSelectedItem()+"';";
            ResultSet rs=stmt.executeQuery(s);
            if(rs.next())
            {
                String comp=rs.getString("carcompany");
                String car=rs.getString("carname");
                txtcomp.setText(comp);
                txtcar.setText(car);
                
            }
            //NO .OF ENTRIES
            
             String c1="Select count(cid) from customer where cid='"+cb.getSelectedItem()+"';";
            ResultSet rs34=stmt.executeQuery(c1);
            int qu=0;
            if(rs34.next())
            {
                int q=rs34.getInt("count(cid)");
                qu=q;
            }
            
            if(qu==0)
            {
                JOptionPane.showMessageDialog(null,"CAR UNSOLD");
            }
           
            
            //DATA FETCH            
            String cust="Select * from customer where cid='"+cb.getSelectedItem()+"';";
            ResultSet rs1=stmt.executeQuery(cust);
          
              String[] stid1 = new String[qu];
               String[] stid2 = new String[qu];
                String[] stid3 = new String[qu];
                 String[] stid4 = new String[qu];
                  String[] stid5 = new String[qu];
                   String[] stid6 = new String[qu];
                    String[] stid7 = new String[qu];
                     String[] stid8 = new String[qu];
                      String[] stid9 = new String[qu];
            int i=0;
            while(rs1.next())
            {
                String nm=rs1.getString("name");
                String lic=rs1.getString("lic");
                String mob=rs1.getString("mob");
                String line1=rs1.getString("line1");
                String area1=rs1.getString("area");
                String landmark=rs1.getString("landmark");
                String city1=rs1.getString("city");
                String state1=rs1.getString("state");
                String pincode=rs1.getString("pincode");
                stid1[i]=nm;
                stid2[i]=lic;
                stid3[i]=mob;
                stid4[i]=line1;
                stid5[i]=area1;
                stid6[i]=landmark;
                stid7[i]=city1;
                stid8[i]=state1;
                stid9[i]=pincode;
                i++;
            }               



                
                
                
                 
                 
                String acc="select * from bookacc where cid='"+cb.getSelectedItem()+"';";
                ResultSet rs2=stmt.executeQuery(acc);
                String[] stid10 = new String[qu];
                String[] stid11 = new String[qu];
                String[] stid12 = new String[qu];
                String[] stid13 = new String[qu];
                String[] stid14 = new String[qu];
                int j=0;
                
                while(rs2.next())
                {
                    String f=rs2.getString("fmid");
                    String s1=rs2.getString("scid");
                    String w=rs2.getString("swid");
                    String b=rs2.getString("basic");
                    String pr=rs2.getString("totalprice");
                    stid10[j]=f;
                    stid11[j]=s1;
                    stid12[j]=w;
                    stid13[j]=b;
                    stid14[j]=pr;
                    j++;
                   
                    
                    
                }
                int l=1;
                for(int k=0;k<qu;k++)
                {
                    Object[] row={l,stid1[k],stid2[k],stid3[k],stid4[k],stid5[k],stid6[k],stid7[k],stid8[k],stid9[k],stid10[k],stid11[k],stid12[k],stid13[k],stid14[k]};
                     my_model.addRow(row);
                     l++;
                }
                
            
         
    
}catch(Exception e)
{
    // JOptionPane.showMessageDialog(null,e);
}
}        // TODO add your handling code here:
    }//GEN-LAST:event_cbActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
    int i=table.getSelectedRow();
int j=table.getSelectedColumn();
String s=table.getValueAt(i,j).toString();
JOptionPane.showMessageDialog(null,s);// TODO add your handling code here:
    }//GEN-LAST:event_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(saleshistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(saleshistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(saleshistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(saleshistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new saleshistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtcar;
    private javax.swing.JTextField txtcomp;
    // End of variables declaration//GEN-END:variables
}
